[project]
name = "optimizer"
version = "0.1.0"
description = "Augmented optimizer for virtual node and game-engine authentication matrix simulation."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT License"}
authors = [
  {name = "Jules", email = "jules@example.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
]
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "pyyaml",
    "click",
    "pytest",
    "flake8",
    "pybullet",
    "networkx",
    "httpx",
    "openai",
    "pymilvus",
    "pytest-asyncio",
    "temporalio",
]

[project.scripts]
omega-inject   = "optimizer.resilience.entropy:main"
omega-stress   = "optimizer.benchmark.availability_stress:main"
lineage-render = "optimizer.dev.mermaid_lineage:main"
service-graph  = "optimizer.dev.service_graph:main"