from setuptools import setup, find_packages

setup(
    name="optimizer",
    version="0.1.0",
    description="Augmented optimizer for virtual node and game-engine authentication matrix simulation.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Jules",
    packages=find_packages(),
    install_requires=[
        "fastapi",
        "uvicorn[standard]",
        "pydantic",
        "pyyaml",
        "click",
        "pytest",
        "flake8",
        "pybullet",
        "networkx",
        "pathspec>=0.12.1",
        "requests>=2.32",
        "beautifulsoup4>=4.12",
        "typer",
        "feedparser",
    ],
    extras_require={
        "atlas": ["PyYAML>=6.0.2", "pathspec>=0.12.1", "requests>=2.32", "beautifulsoup4>=4.12"],
        "dev": ["neo4j", "gitpython", "httpx", "temporalio", "openai", "pytest-asyncio", "pymilvus"],
        "neo4j": ["neo4j"],
    },
    entry_points={
        "console_scripts": [
            "optimizer=optimizer.cli.main:app",
            "map-tree=optimizer.research.tree_mapper:main",
            "api-map=optimizer.apiatlas.cli:map_main",
            "api-health=optimizer.apiatlas.cli:health_main",
            "api-heal=optimizer.apiatlas.cli:heal_main",
            "api-debug=optimizer.apiatlas.cli:debug_main",
            "jules-auto-mutate=optimizer.selflearning.automutator:main",
            "jules-benchmark=optimizer.benchmark.benchmarkrunner:main",
            "jules-risk-scan=optimizer.analytics.risk_classifiers:main",
            "jules-ingest-citations=optimizer.scraper.citation_ingestor:main",
            "jules-service-graph=optimizer.dev.service_graph:main",
            "jules-vault-update=optimizer.dev.vault_updater:main",
            "jules=optimizer.cli.main:app",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
    ],
)
